next-app:
  ~chart: app
  imagePackage: next-app
  probesPath: /
  envFrom:
    - secretRef:
        name: api

pg:
  ~chart: pg

api:
  ~chart: app
  ~needs: ["pg"]
  imagePackage: api
  probesPath: /_health
  containerPort: "1337"

  vars:
    DATABASE_HOST: "$(PGHOST)"
    DATABASE_PORT: "$(PGPORT)"
    DATABASE_NAME: "$(PGDATABASE)"
    DATABASE_USERNAME: "$(PGUSER)"
    DATABASE_PASSWORD: "$(PGPASSWORD)"
    HOST: "0.0.0.0"
    PORT: "1337"
    DATABASE_CLIENT: postgres
    BRANCH_NAME: "{{ .Values.global.branchSlug }}"
  replicas: 1 # mandatory because volume is RWO
  strategyType: Recreate # idem
  securityContext:
    fsGroup: 1000
