next-app:
  ~chart: app
  ~needs: ["build-next-app"]
  imagePackage: next-app
  probesPath: /
  envFrom:
    - secretRef:
        name: api

pg:
  ~chart: pg

api:
  ~chart: app
  ~needs: ["build-api", "pg"]
  imagePackage: api
  probesPath: /_health
  containerPort: "1337"
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: api
    - secretRef:
        name: ozensemble-dev-app-access-key
  vars:
    DATABASE_HOST: "$(PGHOST)"
    DATABASE_PORT: "$(PGPORT)"
    DATABASE_NAME: "$(PGDATABASE)"
    DATABASE_USERNAME: "$(PGUSER)"
    DATABASE_PASSWORD: "$(PGPASSWORD)"
    HOST: "0.0.0.0"
    PORT: "1337"
    DATABASE_CLIENT: postgres
    BRANCH_NAME: "{{ .Values.global.branchSlug }}"
  replicas: 1 # mandatory because volume is RWO
  strategyType: Recreate # idem
  securityContext:
    fsGroup: 1000

jobs:
  runs:
    build-next-app:
      use: build
      ~needs: ["api"]
      with:
        context: ./next-app
        imagePackage: next-app
        buildArgs:
          NEXT_PUBLIC_STRAPI_API_URL: "https://api-{{ .Values.global.host}}"

    build-api:
      use: build
      with:
        imagePackage: api
        context: ./api

deactivate:
  jobs-deactivate:
    runs:
      cleanup-bucket:
        image: bitnami/rclone:latest
        run: |
          rclone purge remote:${BUCKET_NAME}/{{ .Values.global.branchSlug }}
        checkout: false
        env:
          - name: RCLONE_CONFIG_REMOTE_TYPE
            value: s3
          - name: RCLONE_CONFIG_REMOTE_PROVIDER
            value: Other
          - name: RCLONE_CONFIG_REMOTE_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ozensemble-dev-app-access-key
                key: bucket_access_key
          - name: RCLONE_CONFIG_REMOTE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ozensemble-dev-app-access-key
                key: bucket_secret_key
          - name: RCLONE_CONFIG_REMOTE_REGION
            valueFrom:
              secretKeyRef:
                name: ozensemble-dev-app-access-key
                key: bucket_region
          - name: RCLONE_CONFIG_REMOTE_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: ozensemble-dev-app-access-key
                key: bucket_endpoint
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: ozensemble-dev-app-access-key
                key: bucket_name
